Repository griddynamics/ui-intshp2-cp-okapi, pull requests merged in 2019-02, with the labels that each got.

#21 [Pavlo Turchyn]UIT-44 related products initial commit
  src/app/core/services/data.service.ts
  src/app/core/services/product-details-page.service.spec.ts
  src/app/core/services/product-details-page.service.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.html
  src/app/product-details-page/components/product-details-page/product-details-page.component.spec.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.ts
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.spec.ts
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
  src/app/product-details-page/product-details-page.module.ts
  src/app/shared/components/advertising-area/advertising-area.component.spec.ts
  src/app/shared/interfaces/product.ts
  src/app/shared/pipes/safe.pipe.spec.ts
  src/app/shared/pipes/safe.pipe.ts
  src/app/shared/shared.module.ts
  src/assets/mocks/pdp.json
Labels: Ready for merge

#16 [TARAS YAKYMIUK]wishlist + localstorage + added product items service
  src/app/core/services/data.service.ts
  src/app/core/services/product-details-page.service.ts
  src/app/core/services/products.service.spec.ts
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.scss
  src/app/home-page/components/home-page/home-page.component.spec.ts
  src/app/home-page/components/home-page/home-page.component.ts
  src/app/home-page/components/wish-list/wish-list.component.html
  src/app/home-page/components/wish-list/wish-list.component.scss
  src/app/home-page/components/wish-list/wish-list.component.spec.ts
  src/app/home-page/components/wish-list/wish-list.component.ts
  src/app/home-page/home-page.module.ts
  src/app/product-details-page/components/product-description/product-description.component.html
  src/app/product-details-page/components/product-description/product-description.component.ts
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.html
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.spec.ts
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.html
  src/app/product-details-page/components/product-description/product-order/product-order.component.spec.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.html
  src/app/product-details-page/components/product-details-page/product-details-page.component.spec.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.ts
  src/app/product-details-page/product-details-page.module.ts
  src/app/shared/components/carousel/carousel.component.spec.ts
  src/app/shared/components/carousel/carousel.component.ts
  src/app/shared/components/load-more/load-more.component.html
  src/app/shared/components/load-more/load-more.component.scss
  src/app/shared/components/load-more/load-more.component.spec.ts
  src/app/shared/components/load-more/load-more.component.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item-short/product-item-short.component.scss
  src/app/shared/components/product-item/product-item-short/product-item-short.component.ts
  src/app/shared/components/product-item/product-item.component.ts
  src/app/shared/interfaces/product.ts
  src/app/shared/shared.module.ts
  src/assets/mocks/pdp.json
  src/assets/mocks/products.json
Labels: Ready for merge

#26 [Nataliya Mykytyuk] Feature flags
  src/app/app.module.ts
  src/app/core/services/killswitch.service.spec.ts
  src/app/core/services/killswitch.service.ts
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.ts
  src/app/product-details-page/components/product-description/product-image-preview/zoom/zoom.component.scss
  src/app/product-details-page/components/product-description/product-order/product-order.component.html
  src/app/product-details-page/components/product-description/product-order/product-order.component.scss
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.spec.ts
  src/app/shared/components/product-item/product-item.component.html
  src/app/shared/components/product-item/product-item.component.spec.ts
  src/app/shared/components/product-item/product-item.component.ts
  src/assets/config/killswitches.json
  src/assets/mocks/pdp.json
Labels: Ready for merge, Ready for review

#23 [Natalia Falinska] UIT 34 recently viewed
  package-lock.json
  package.json
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.ts
  src/app/shared/components/carousel/carousel.component.scss
  src/app/shared/components/carousel/carousel.component.spec.ts
  src/app/shared/components/carousel/carousel.component.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.scss
  src/app/shared/components/recently-viewed/recently-viewed.component.html
  src/app/shared/components/recently-viewed/recently-viewed.component.scss
  src/app/shared/components/recently-viewed/recently-viewed.component.spec.ts
  src/app/shared/components/recently-viewed/recently-viewed.component.ts
  src/app/shared/shared.module.ts
Labels: Ready for review

#28 [Natalia Falinska] Style for JOIN US
  src/app/shared/components/join-us/join-us.component.html
  src/app/shared/components/join-us/join-us.component.scss
Labels: Ready for merge

#27 [taras yakymiuk] Hotfix wishlist
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/wish-list/wish-list.component.html
  src/app/home-page/components/wish-list/wish-list.component.spec.ts
Labels: Bug, Ready for merge

#29 [Natalia Falinska] added joinus to pdp
  src/app/product-details-page/components/product-details-page/product-details-page.component.html
  src/app/shared/components/join-us/join-us.component.ts
Labels: Bug, Ready for merge

#30 [Nataliya Mykytyuk] Product List Page (uit-46)
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.scss
  src/app/product-list-page/components/product-list-page/product-list-page.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/product-list-page/product-list-page-routing.module.ts
  src/app/product-list-page/product-list-page.component.html
  src/app/product-list-page/product-list-page.component.scss
  src/app/product-list-page/product-list-page.module.ts
Labels: Ready for merge

#31 [Nataliya Mykytyuk] Spinner
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/services/loader.service.spec.ts
  src/app/core/services/loader.service.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.html
  src/app/shared/components/carousel/carousel.component.spec.ts
  src/app/shared/components/carousel/carousel.component.ts
  src/app/shared/components/loader/loader.component.html
  src/app/shared/components/loader/loader.component.scss
  src/app/shared/components/loader/loader.component.spec.ts
  src/app/shared/components/loader/loader.component.ts
  src/app/shared/components/loader/loader.interceptor.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item.component.html
  src/app/shared/components/product-item/product-item.component.spec.ts
  src/app/shared/shared.module.ts
  src/assets/mocks/products.json
  src/index.html
  src/styles.scss
Labels: Ready for merge

#33 [Pavlo Turchyn] uit-43_Control_slideshow_slide_transition_effect_under_killswitch_flag
  src/app/home-page/components/slideshow/slideshow.component.spec.ts
  src/app/home-page/components/slideshow/slideshow.component.ts
  src/assets/config/killswitches.json
  src/assets/img/slideshow/banner-main1-1540x650.jpg
  src/assets/img/slideshow/banner-main2-1540x650.jpg
  src/assets/img/slideshow/forged-ground-featured-official-merch-es-1540x650.jpg
  src/assets/img/slideshow/viking-medieval-escudos-cascos-cuernos-espadass-accesorios-forgedground-1540x650.jpg
Labels: Ready for merge

#38 [Pavlo Turchyn] created img-placeholder component
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/slideshow/slideshow.component.html
  src/app/home-page/components/slideshow/slideshow.component.spec.ts
  src/app/shared/components/advertising-area/advertising-area.component.html
  src/app/shared/components/advertising-area/advertising-area.component.spec.ts
  src/app/shared/components/advertising-area/advertising-area.component.ts
  src/app/shared/components/img-placeholder/img-placeholder.component.html
  src/app/shared/components/img-placeholder/img-placeholder.component.scss
  src/app/shared/components/img-placeholder/img-placeholder.component.spec.ts
  src/app/shared/components/img-placeholder/img-placeholder.component.ts
  src/app/shared/shared.module.ts
Labels: Ready for merge

#32 [Artur Kostiuk] uit 42 product grid
  package-lock.json
  package.json
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.scss
  src/app/home-page/components/home-page/home-page.component.spec.ts
  src/app/home-page/components/wish-list/wish-list.component.html
  src/app/home-page/components/wish-list/wish-list.component.spec.ts
  src/app/home-page/components/wish-list/wish-list.component.ts
  src/app/product-details-page/components/product-description/product-description.component.scss
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.scss
  src/app/product-list-page/components/product-list-page/product-list-page.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/product-list-page/product-list-page.module.ts
  src/app/shared/components/grid/grid.component.html
  src/app/shared/components/grid/grid.component.scss
  src/app/shared/components/grid/grid.component.spec.ts
  src/app/shared/components/grid/grid.component.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item.component.html
  src/app/shared/components/product-item/product-item.component.scss
  src/app/shared/shared.module.ts
  src/assets/mocks/products.json
Labels: Ready for review

#39 [Pavlo Turchyn]page not found component updated
  src/app/page-not-found/page-not-found.component.html
  src/app/page-not-found/page-not-found.component.scss
  src/app/page-not-found/page-not-found.component.ts
  src/app/shared/shared.module.ts
  src/assets/404-Airbnb_final-d652ff855b1335dd3eedc3baa8dc8b69.gif
Labels: Changes requested

#40 [Artur Kostiuk] fix add to wish list
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
Labels: Ready for merge

#34 [Natalia Falinska] lazy load
  package-lock.json
  src/app/home-page/components/home-page/home-page.component.spec.ts
  src/app/home-page/components/slideshow/slideshow.component.html
  src/app/home-page/components/slideshow/slideshow.component.scss
  src/app/home-page/components/slideshow/slideshow.component.spec.ts
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.spec.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.spec.ts
  src/app/shared/components/carousel/carousel.component.html
  src/app/shared/components/carousel/carousel.component.spec.ts
  src/app/shared/components/lazy-load/lazy-load.component.html
  src/app/shared/components/lazy-load/lazy-load.component.scss
  src/app/shared/components/lazy-load/lazy-load.component.spec.ts
  src/app/shared/components/lazy-load/lazy-load.component.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item-short/product-item-short.component.scss
  src/app/shared/components/product-item/product-item-short/product-item-short.component.spec.ts
  src/app/shared/components/product-item/product-item.component.html
  src/app/shared/components/product-item/product-item.component.spec.ts
  src/app/shared/components/product-item/product-item.component.ts
  src/app/shared/interfaces/product.ts
  src/app/shared/shared.module.ts
Labels: Ready for merge

#37 [Nataliya Mykytyuk] UIT-41 Faceted Navigation
  package-lock.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.scss
  src/app/product-list-page/components/product-list-page/product-list-page.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/product-list-page/product-list-page.module.ts
  src/app/shared/interfaces/product.ts
  src/styles.scss
Labels: Ready for merge

#42 [Nataliya Mykytyuk] Fixes of product item
  src/app/shared/components/product-item/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item-short/product-item-short.component.scss
  src/app/shared/components/product-item/product-item.component.html
  src/app/shared/components/product-item/product-item.component.scss
  src/app/shared/components/product-item/product-item.component.spec.ts
Labels: Ready for merge

#44 [Nataliya Mykytyuk] Responsive sidebar
  package-lock.json
  package.json
  src/app/core/services/products.service.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.scss
  src/app/shared/components/grid/grid.component.scss
  src/app/shared/components/grid/grid.component.ts
  src/app/shared/components/product-item/product-item.component.scss
Labels: Ready for review

#46 [Nataliya Mykytyuk] Swipe icon
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.scss
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.scss
  src/app/shared/components/product-item/product-item-short/product-item-short.component.scss
  src/app/shared/components/swipe-icon/swipe-icon.component.html
  src/app/shared/components/swipe-icon/swipe-icon.component.scss
  src/app/shared/components/swipe-icon/swipe-icon.component.spec.ts
  src/app/shared/components/swipe-icon/swipe-icon.component.ts
  src/app/shared/shared.module.ts
Labels: Ready for review

#47 fixes
  package.json
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.ts
  src/app/shared/components/loader/loader.component.scss
Labels: Ready for review

#49 [TARAS YAKYMIUK]added readme to api
  README.md
  src/server/README.md
Labels: Ready for review

#48 [Pavlo Turchyn] Slideshow, banners, arrivals, recently viewed, wish-list, PLP grid, PDP API integration
  src/app/core/services/killswitch.service.ts
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.spec.ts
  src/app/home-page/components/home-page/home-page.component.ts
  src/app/home-page/components/recently-viewed/recently-viewed.component.html
  src/app/home-page/components/recently-viewed/recently-viewed.component.ts
  src/app/home-page/components/slideshow/slideshow.component.html
  src/app/home-page/components/slideshow/slideshow.component.scss
  src/app/home-page/components/slideshow/slideshow.component.ts
  src/app/home-page/components/wish-list/wish-list.component.html
  src/app/home-page/components/wish-list/wish-list.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/shared/components/advertising-area/advertising-area.component.html
  src/app/shared/components/advertising-area/advertising-area.component.ts
  src/assets/mocks/products.json
  src/assets/mocks/slideshow.json
  src/environments/environment.mock.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/server/controller.js
Labels: Ready for review

#50 [Artur Kostiuk]uit 64 swatch selection
  src/app/product-details-page/components/product-description/product-description.component.html
  src/app/product-details-page/components/product-description/product-description.component.ts
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.html
  src/app/product-details-page/components/product-description/product-order/product-order.component.scss
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
Labels: Ready for merge

#53 [Artur Kostiuk]bug fix uit 64
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
Labels: Bug, Ready for merge

#55 [Nataliya Mykytyuk] Spinner setTimeout
  src/app/core/services/loader.service.spec.ts
  src/app/core/services/loader.service.ts
Labels: Ready for merge

#54 [ONLY FOR TEST] Travis CI WIP
  .travis.yml
  README.md
  src/app/core/services/loader.service.spec.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.html
  src/assets/config/killswitches.json
  src/karma.conf.js
Labels: Ready for merge
