Repository griddynamics/ui-intshp2-cp-okapi, pull requests merged in 2019-03, with the labels that each got.

#43 [Artur Kostiuk] uit 47 add to cart
  src/app/core/components/header/header-nav/header-nav.component.html
  src/app/core/components/header/header-nav/header-nav.component.spec.ts
  src/app/core/components/header/header-nav/header-nav.component.ts
  src/app/core/components/header/header.component.spec.ts
  src/app/core/decorators/product.ts
  src/app/core/services/cart.service.ts
  src/app/core/services/product-details-page.service.ts
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.ts
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.html
  src/app/product-details-page/components/product-description/product-order/product-order.component.scss
  src/app/product-details-page/components/product-description/product-order/product-order.component.spec.ts
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.spec.ts
  src/app/product-details-page/components/product-details-page/product-details-page.component.ts
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
  src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/shared/components/index.ts
  src/app/shared/components/product-item/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item-short/product-item-short.component.ts
  src/app/shared/components/product-item/product-item.component.html
  src/app/shared/components/product-item/product-item.component.scss
  src/app/shared/components/product-item/product-item.component.ts
  src/app/shared/interfaces/index.ts
  src/app/shared/interfaces/product.ts
  src/server/controller.js
Labels: Ready for merge

#60 [TARAS YAKYMIUK] Uit 65 handle product in stock
  src/app/product-details-page/components/product-description/product-order/product-order.component.ts
  src/app/shared/interfaces/product.ts
  src/assets/mocks/products.json
Labels: Ready for merge

#57 [Pavlo Turchyn]Uit 61-Integrate PLP filters
  src/app/core/services/products.service.spec.ts
  src/app/core/services/products.service.ts
  src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/base-filter.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/checkbox-filter/checkbox-filter.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.scss
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/faceted-navigation.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/price-range-filter/price-range-filter.component.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.html
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.spec.ts
  src/app/product-list-page/components/product-list-page/faceted-navigation/radio-filter/radio-filter.component.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/shared/interfaces/product.ts
  src/server/controller.js
Labels: Merge conflicts, Ready for merge

#63 [Pavlo Turchyn]Uit 73 slider bug transition
  src/app/core/services/products.service.ts
  src/app/home-page/components/slideshow/slideshow.component.scss
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/shared/interfaces/product.ts
Labels: Ready for review

#67 [Pavlo Turchyn]uit-76 fixed edges in slideshow
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/slideshow/slideshow.component.scss
  src/assets/config/killswitches.json
Labels: Ready for merge

#68 [Pavlo Turchyn]uit-74 fixed total bug & no-products fix
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/shared/components/heading/heading.component.html
  src/app/shared/components/heading/heading.component.ts
  src/assets/coolio_dribbble.gif
  src/server/controller.js
Labels: Ready for merge

#65 [Artur Kostiuk]uit 69 loading on scroll
  src/app/product-list-page/components/product-list-page/product-list-page.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/assets/config/killswitches.json
Labels: Ready for merge

#64 fixed wishlist behavior
  src/app/core/services/products.service.spec.ts
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/home-page/home-page.component.spec.ts
  src/app/home-page/components/home-page/home-page.component.ts
  src/app/home-page/components/wish-list/wish-list.component.html
  src/app/home-page/components/wish-list/wish-list.component.ts
  src/app/shared/components/grid/grid.component.ts
  src/app/shared/decorators/product.ts
Labels: Ready for merge

#69 [Artur Kostiuk]bug fix in load on scroll
  package-lock.json
  package.json
  src/app/core/services/data.service.ts
  src/app/core/services/products.service.ts
  src/app/home-page/components/home-page/home-page.component.html
  src/app/home-page/components/recently-viewed/recently-viewed.component.html
  src/app/product-details-page/components/related-products/related-products.component.spec.ts
  src/app/product-details-page/components/related-products/related-products.component.ts
  src/app/product-list-page/components/checkbox-filter/checkbox-filter.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.html
  src/app/product-list-page/components/product-list-page/product-list-page.component.spec.ts
  src/app/product-list-page/components/product-list-page/product-list-page.component.ts
  src/app/product-list-page/components/radio-filter/radio-filter.component.html
  src/app/shared/components/grid/grid.component.spec.ts
  src/app/shared/components/load-more/load-more.component.html
  src/app/shared/components/load-more/load-more.component.scss
  src/app/shared/components/load-more/load-more.component.spec.ts
  src/app/shared/components/load-more/load-more.component.ts
  src/app/shared/components/product-item-short/product-item-short.component.html
  src/app/shared/components/product-item/product-item.component.html
  src/polyfills.ts
  src/styles.scss
Labels: Bug, Changes requested, Merge conflicts

#61 [Natalia Falinska] UIT-54 popup v2 !!Without tests
  package-lock.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/core/components/header-nav/header-nav.component.html
  src/app/core/components/header-nav/header-nav.component.ts
  src/app/core/core.module.ts
  src/app/core/services/cart.service.ts
  src/app/core/services/index.ts
  src/app/core/services/modal.service.spec.ts
  src/app/core/services/modal.service.ts
  src/app/product-details-page/components/product-order/product-order.component.ts
  src/app/shared/components/index.ts
  src/app/shared/components/modal-window/modal-context.spec.ts
  src/app/shared/components/modal-window/modal-context.ts
  src/app/shared/components/modal-window/modal-window.component.html
  src/app/shared/components/modal-window/modal-window.component.scss
  src/app/shared/components/modal-window/modal-window.component.spec.ts
  src/app/shared/components/modal-window/modal-window.component.ts
  src/app/shared/components/product-item/product-item.component.ts
  src/app/shared/components/shopping-cart/shopping-cart.component.html
  src/app/shared/components/shopping-cart/shopping-cart.component.scss
  src/app/shared/components/shopping-cart/shopping-cart.component.spec.ts
  src/app/shared/components/shopping-cart/shopping-cart.component.ts
  src/app/shared/directives/modal-holder.directive.ts
  src/app/shared/interfaces/index.ts
  src/app/shared/interfaces/product.ts
  src/app/shared/shared.module.ts
  src/assets/empty-bag.gif
  src/assets/empty-bag2.gif
  src/assets/mocks/products.json
  src/scss/_reset.scss
Labels: Ready for merge

#71 [Natalia Falinska] Fixed bug for popup
  src/app/core/services/modal.service.ts
  src/app/shared/components/index.ts
  src/app/shared/components/modal-window/modal-window.component.spec.ts
  src/app/shared/components/modal-window/modal-window.component.ts
  src/app/shared/components/product-item/product-item.component.ts
  src/app/shared/components/shopping-cart/shopping-cart.component.spec.ts
Labels: Ready for merge

#70 [Artur Kostiuk] bug fix in add to cart component
  src/app/product-details-page/components/product-description/product-description.component.spec.ts
  src/app/product-details-page/components/product-image-preview/product-image-preview.component.html
  src/app/product-details-page/components/product-image-preview/product-image-preview.component.scss
  src/app/product-details-page/components/product-image-preview/product-image-preview.component.ts
  src/app/product-details-page/components/product-order/product-order.component.html
  src/app/product-details-page/components/product-order/product-order.component.scss
  src/app/product-details-page/components/product-order/product-order.component.ts
  src/app/shared/components/product-item/product-item.component.ts
Labels: Bug, Ready for merge

#72 [Taras Yakymiuk]Error handling
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/services/data.service.ts
  src/app/core/services/error.service.spec.ts
  src/app/core/services/error.service.ts
  src/app/core/services/global-error-handler.service.spec.ts
  src/app/core/services/global-error-handler.service.ts
  src/app/core/services/logging.service.spec.ts
  src/app/core/services/logging.service.ts
  src/app/core/services/notification.service.spec.ts
  src/app/core/services/notification.service.ts
  src/app/core/services/server-error.interceptor.ts
  src/app/page-not-found/page-not-found.component.ts
  src/server/controller.js
  src/styles.scss
Labels: Changes requested, Ready for merge

#75 Fix decorators bug for add to cart
  src/app/core/services/cart.service.ts
  src/app/core/services/global-error-handler.service.spec.ts
  src/app/core/services/notification.service.spec.ts
  src/app/product-details-page/components/product-order/product-order.component.ts
  src/app/shared/components/shopping-cart/shopping-cart.component.html
  src/app/shared/components/shopping-cart/shopping-cart.component.ts
Labels: Ready for review

#73 [Natalia Falinska] UIT 58 integrate join us
  package-lock.json
  package.json
  src/app/core/services/cart.service.ts
  src/app/core/services/notification.service.spec.ts
  src/app/shared/components/join-us/join-us.component.html
  src/app/shared/components/join-us/join-us.component.ts
  src/app/shared/components/shopping-cart/shopping-cart.component.ts
  src/server/controller.js
  src/server/router.js
Labels: Merge conflicts, Ready for review

#74 [Artur Kostiuk] Bug in cart product
  package-lock.json
  src/app/core/services/cart.service.ts
  src/app/product-details-page/components/product-order/product-order.component.ts
Labels: Bug, Ready for review

#66 [Nataliya Mykytyuk] Bug uit-77 Product-item in carousel
  src/app/home-page/components/recently-viewed/recently-viewed.component.scss
  src/app/home-page/components/wish-list/wish-list.component.html
  src/app/shared/components/grid/grid.component.html
  src/app/shared/components/grid/grid.component.scss
  src/app/shared/components/grid/grid.component.ts
  src/app/shared/components/product-item-short/product-item-short.component.scss
  src/karma.conf.js
Labels: Bug, Merge conflicts

#77 [Pavlo Turchyn]uit 52 angular cli service worker
  angular.json
  ngsw-config.json
  package.json
  src/app/app.module.ts
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/index.html
  src/manifest.webmanifest
Labels: Ready for review
